module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts

params:
  offices:
    thumbnail:
      desktop: "522x345"
      mobile: "300x198"
      scrollsnap: "240x158"
    image:
      desktop: "416x"
      mobile: "198x"

# Default
permalinks:
  tags: /offices/:slug/
taxonomies:
  office: offices